## prometheus-eventhubs-adapter
## Settings file in TOML (https://github.com/toml-lang/toml)
##
## All settings are #commented out, uncomment settings you want to define.
## See project for additional documentation: https://github.com/bryanklewis/prometheus-eventhubs-adapter

## -------------------- Adapter --------------------
#connection_timeout = "5s" # Units: "ns", "ms", "s", "m", "h"
#listen_address = ":9201"
#write_path = "/write"
#telemetry_path = "/metrics"
#log_level = "info"

## -------------------- Event Hub Writer --------------------
#write_batch = true
#write_adxmapping = "promMap"
#write_serializer = "json"
